### ISSUE TITLE
Is there a way to get the progress of downloads in a queue?

### ISSUE THREAD

**Issue by OutRunner** [daltoniam/SwiftHTTP#106]
Hello,

First of all, thanks for such a great framework, it's made downloading files from a server so easy!

I've been looking at your examples for getting the progress of a download and of adding multiple downloads to a queue, however I can't seem to find a way to add an HTTPTask.download() to an NSOperationQueue. 

Basically I'm trying to update a load of UIProgressViews to show the progress of my various file downloads and when they're all done I need to be able to detect this to move the app on to the next stage.

I'm new to Swift so I'm probably missing something simple, but is there a way I can either tell when all my HTTPTask.downloads are finished or get the progress of downloads when using HTTPTask.create?

Many thanks again!
Si

**Comment by daltoniam** [comment]
The `download` method works a tad different the the normal `create` methods, as it uses the background APIs. I left a comment in the code on the being queuable part:

https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L339

I didn't expect the use case you are bringing up. Since the NSOperationQueue isn't an option with the `download()` method, I would recommend doing something like so:

```swift
let totalDownloads = 5
var downloadCount = 0
let finished = { () -> Void in
    downloadCount++
    if downloadCount == totalDownloads {
        println("all downloads completed!")
        //move to your next section
    }
}

var request = HTTPTask()
let downloadTask = request.download("http://domain.com/download1", parameters: nil, progress: {(complete: Double) in
    //update the progress view
    }, completionHandler: {(response: HTTPResponse) in
    //A download completed!
    finished()
})

//do download 2
let downloadTask2 = request.download("http://domain.com/download2", parameters: nil, progress: {(complete: Double) in
    //update the progress view
    }, completionHandler: {(response: HTTPResponse) in
    //A download completed!
    finished()
})
//repeat for all the downloads
```
You could of course clean this up with a loop and a function to not repeat so much, but the should give you the general idea. You have a closure that gets notified when all the downloads complete and you can move to your next section.

**Comment by OutRunner** [comment]
Thanks so much for the code, that's worked perfectly! I should have thought of something like this but I was so focused on queues I didn't step back to think about alternatives.

Thanks again!
Si

**Comment by daltoniam** [comment]
:+1:
