### ISSUE TITLE
Upload with JSONParameterSerializer

### ISSUE THREAD

**Issue by lobodart** [daltoniam/SwiftHTTP#173]
Hey Dalton ! First, thanks for the Swift 2.0 update ;)
I have a question : How can I upload an image even using the JSONParameterSerializer ? Is it possible ? Is there an other way to upload both (image and JSON elements) ?

Thanks in advance for your answer,
Louis

**Comment by acmacalister** [comment]
Hey Louis,

I'm not sure SwiftHTTP was designed to do that. I would assume the image is binary and you really can't have that inside a JSON payload unless you are base64 encoding or something along those lines? Or maybe I'm overlooking something?

**Comment by acmacalister** [comment]
I know I'm not Dalton, but I do share some similarities. :smile:

**Comment by lobodart** [comment]
Thanks @acmacalister :) So, according to you it's impossible ? Or maybe I need to send 2 different requests ?

**Comment by acmacalister** [comment]
Well, I wouldn't say just according to me (what do I know :smile: ), but according to the [JSON RFC spec](https://tools.ietf.org/html/rfc7159):

`JavaScript Object Notation (JSON) is a text format for the serialization of structured data...`

Being a text based serialization format it can't encode raw binary data. So that would leave us with 3 options.

1. Two different requests like you suggested. One with a multipart form encoding for the file and the other for JSON. Or even better would be if you could move the JSON into form params and avoid a second request altogether.

2. Use a different serialization format that supports binary. Popular options are [BSON](http://bsonspec.org), [protobuf](https://developers.google.com/protocol-buffers/) and [msg-pack](http://msgpack.org/index.html).

3. Base64 encode the file data in your JSON. Base64 is a text representation of data which you could embed in your JSON.

If I were to rate these on which one I would use, I would probably go from 1 to 3. 1 being my favorite and 3 being my least.
