### ISSUE TITLE
URLEncoding of "plus" (+) sign

### ISSUE THREAD

**Issue by S4TNEW** [daltoniam/SwiftHTTP#178]
Hi,
when adding a post parameter that includes a plus sign ("+") that sign is not encoded properly.
So at server side it still appears as a plus and then is interpreted as an space.

I think the String extension "escaped" has to be edited as the used method "stringByAddingPercentEncodingWithAllowedCharacters" doesn't handle specific signs as the plus.

**Comment by acmacalister** [comment]
Turns out `NSCharacterSet.URLQueryAllowedCharacterSet()` only encodes for the RFC 1738 (and additions), not the HTTP spec like one might expect. For future reference:

http://www.ietf.org/rfc/rfc1738.txt

plus characters "+" (and friends) are legal in a URL and will not be encoded according to the RFC spec. HTTP however expects them to be encoded, as listed here:

http://www.w3.org/TR/html5/forms.html#application/x-www-form-urlencoded-encoding-algorithm

Thanks for the report.
