### ISSUE TITLE
How do you include JSON in the body?

### ISSUE THREAD

**Issue by n8sabes** [daltoniam/SwiftHTTP#184]
Thanks for the great work on SwiftHTTP and for maintaining iOS 7 support.

I can't seem to find a functional example of how to include JSON in the body of a request and the closed issue (#79) doesn't seem to work. Can provide an example or update the docs to include one?

**Comment by reshadf** [comment]
This should work. 
    do {
            let opt = try HTTP.New("url", method: .GET, parameters: nil, headers: nil, requestSerializer: JSONParameterSerializer())
            
            opt.start { response in
                if let err = response.error {
                    print("error: \(err.localizedDescription)")
                    print("opt finished with error info: \(response.description)")
                }
                    print("opt finished with info: \(response.description)")
            }
        }  catch let error {
            print("\(error)")
        }

**Comment by n8sabes** [comment]
Thanks reshadf.

Suppose the POST request body is to contain the following JSON: {"foo_1" : "bar_1", "foo_2" : "bar_2"}. Where would that be plugged into the example code to send the payload up to the server?

**Comment by reshadf** [comment]
It should be a dictionary so yes something like 
    let json = ["key" : "Value", "Key" : "Value"]

Then you should give that json in the parameters along with the request. 

    let opt = try HTTP.New("url", method: .GET, parameters: json, headers: nil, requestSerializer: JSONParameterSerializer())

**Comment by daltoniam** [comment]
@reshadf Thanks, appreciate the help. 
@reshadf is correct, the `JSONParameterSerializer()` should do this. It will handle converting a Dictionary or Array into the proper JSON representation using `NSJSONSerialization`.

**Comment by syscaday** [comment]
@n8sabes I know what you requested... Im also searching for that..
@daltoniam I'm finding on how to send a POST request with HTTP BODY involve (mean payload)
he reason why not parameter I'm using is because URL length are limited, my parameter may more than that, so i decided to use HTTP BODY as my parameter (JSON content). My URL will no carry any parameter mean that from this 

"http://exampleRest.com?param1=testValue" 

become this

"http://exampleRest.com" for the HTTP BODY part
{ "param1": "testValue" }


Question here is, anyway i can use SwiftHTTP to include HTTP BODY instead of parameter? As you mention JSONParameterSerializer() can perform this. Can provide any example on this?

Thanks on your project, it very useful. hope listen to you SAP

**Comment by daltoniam** [comment]
@syscaday right, I am aware of this. Using the HTTPBody for POST request is the default behavior in SwiftHTTP see here:

https://github.com/daltoniam/SwiftHTTP/blob/master/Request.swift#L310

The only exception are the ones that required by the HTTP spec `isURIParam` ones.

https://github.com/daltoniam/SwiftHTTP/blob/master/Request.swift#L327

Thus the examples that are provided above or in the README should give the desired behavior.

**Comment by syscaday** [comment]
@daltoniam thank you very much, i success perform HTTP POST with body.
great work!!!!!
