### ISSUE TITLE
sending nil values in JSON request

### ISSUE THREAD

**Issue by tony7126** [daltoniam/SwiftHTTP#233]
here the parameters are attempted to being cast as an AnyObject before being serialized:
[https://github.com/daltoniam/SwiftHTTP/blob/master/Source/Request.swift#L333](url)

But if there is a nil value set for one of the keys in the param dictionary you get an error:

> Could not cast value of type 'Swift.Dictionary<Swift.String, Swift.Optional<Swift.AnyObject>>' (0x1105fe1a0) to 'Swift.AnyObject' (0x1105ef050)

**Comment by daltoniam** [comment]
I hadn't considered nil being inserted as a parameter, but I guess I could see that happening with the JSON serializer. Currently it doesn't support nil as the assumption would be just not to send the key, but that probably doesn't handle all use cases. PR is welcomed if you want to add support, otherwise I will work on it when I start a Swift 3 refactor.

**Comment by daltoniam** [comment]
So I thought more about this and I think the better option that allowing nil (and thus making every parameter optional) would be to insert a `NSNull` type. I believe then the JSON serializer would convert that to nil as desired.
