### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Cyphontin** [daltoniam/SwiftHTTP#266]
Hello,
At each request the memory increases, but never decreases.
BR

**Comment by acmacalister** [comment]
Do you have any code examples or actual debugging done to reproduce this issue? This doesn't give us anything to go off.

**Comment by Cyphontin** [comment]
Each time I do a request the memory goes up, and even if you wait 2 hours never decrease, so imagine if you do 1000 requests.

 @IBAction func Click(_ sender: Any)
    {
        let params = ["recu": "test1", "recu2": "test2"]
        do {
            let opt = try HTTP.POST("https://yourdomain.xxx/peroquet.php", parameters: params)
            opt.start { response in
                if let err = response.error {
                    print("error: \(err.localizedDescription)")
                    return //also notify app of failure as needed
                }
                print("opt finished: \(response.description)")
            }
        } catch let error {
            print("got an error creating the request: \(error)")
        }

    }

![capture d ecran 2017-03-03 a 20 57 01](https://cloud.githubusercontent.com/assets/22193771/23568914/cbd7a74a-0054-11e7-926d-f8f0e459c592.png)

**Comment by acmacalister** [comment]
Ok, I understand your reasoning, but we actually have to debug if there is a memory leak somewhere in the library. Just looking at the graphs and assuming there is a leak because the memory doesn't decrease isn't a reliable way to reproduce this. I will try and debug this on my end using the memory profiler and leak detector to do some real analysis. If you would like to do the same that would great.

**Comment by Cyphontin** [comment]
I tried to find it without success, It should be a strong reference.
Thank you , life long and prosper ;)
