### ISSUE TITLE
post can't pass paramters php server success

### ISSUE THREAD

**Issue by gaoml0904** [daltoniam/SwiftHTTP#284]
'''
let paramsEn = ["en":"params"]
HTTP.POST(serviceURL, parameters: paramsEn, headers: nil, requestSerializer: JSONParameterSerializer(), completionHandler: { (response) in
})
'''
I use above code to post. the server side with php can't receive the parameters.who can help

**Comment by daltoniam** [comment]
If your server isn't receiving the HTTP request you made, I would check to ensure your serviceURL is correct and that your device has a connection to reach the server. You should get an error if the request fails telling you what the issue is. Those are my recommendations based on the information provided, but this is probably an environment issue rather than an issue with the library.

**Comment by sotoudegan** [comment]
Hi
I have same problem. I have request with json parameters as html body, Server received my http request, but it coudln't get the parameters
