### ISSUE TITLE
If credentials wrong, HTTPTask will try to use incorrect credentials repeatedly

### ISSUE THREAD

**Issue by robertmryan** [daltoniam/SwiftHTTP#46]
Pursuant to http://stackoverflow.com/q/27949677/1271826, the `didReceiveChallenge` should probably only try a particular set of credentials once. If they were wrong, the existing implementation would try repeatedly. 

Therefore, I might suggest changing:

    public func URLSession(session: NSURLSession, task: NSURLSessionTask, didReceiveChallenge challenge: NSURLAuthenticationChallenge, completionHandler: (NSURLSessionAuthChallengeDisposition, NSURLCredential!) -> Void) {
        if let a = auth {
            let cred = a(challenge)
            if let c = cred {
                completionHandler(.UseCredential, c)
                return
            }
            completionHandler(.RejectProtectionSpace, nil)
            return
        }
        completionHandler(.PerformDefaultHandling, nil)
    }

To:

    public func URLSession(session: NSURLSession, task: NSURLSessionTask, didReceiveChallenge challenge: NSURLAuthenticationChallenge, completionHandler: (NSURLSessionAuthChallengeDisposition, NSURLCredential!) -> Void) {
        if let credential = auth?(challenge) {
            if challenge.previousFailureCount == 0 {
                completionHandler(.UseCredential, credential)
            } else {
                completionHandler(.RejectProtectionSpace, nil)
            }
        } else {
            completionHandler(.PerformDefaultHandling, nil)
        }
    }

This will only try using the credentials provided once.

**Comment by daltoniam** [comment]
Looking at the StackOverflow question, it appeared it was because an old version of SwiftHTTP was being used. I agree that generally that would be the common use case, but the current system is designed to support multiple authentication attempts as well.

The README includes an auth example that does the same thing, but would allow the flexibility to try multiple log attempts if desired (I do believe that would be very uncommon).
https://github.com/daltoniam/SwiftHTTP#authentication

The current system and example will handle all edge cases I am aware of, but please let me know if I am missing a possible case.

**Comment by robertmryan** [comment]
It seems curious to place the burden on the app developer to have to write a closure that implements its own retry logic (especially because that is an edge case), but if that's your call.
